test:
  image: registry.gitlab.com/matthieusegret/yummy-phoenix-graphql/ci:1.1

  services:
    - postgres:latest

  variables:
    POSTGRES_DB: yummy_graphql_test
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "postgres"
    MIX_ENV: "test"

  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - deps
      - _build
      - client/node_modules
      - client/build

  before_script:
    - fakes3 -r .s3bucket -p 4567 > /dev/null 2>&1 &
    - npm run build
    - npm run test.server  > /dev/null 2>&1 &
    - mix deps.get --only test
    - mix ecto.migrate

  script:
    - mix test