apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - yummy-gateway
  http:
  - match:
    - uri:
        exact: /graphql
    route:
    - destination:
        host: api-svc
        port:
          number: 80