apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 80
    targetPort: 80