apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
type: Opaque
data:
  node-cookie: {{ randAlphaNum 48 | b64enc | quote }}
  secret-key-base: {{ randAlphaNum 48 | b64enc | quote }}
  sendgrid-api-key: {{ .Values.api.sendgridApiKey | b64enc | quote }}
  s3-key: {{ .Values.api.s3Key | b64enc | quote }}
  s3-secret: {{ .Values.api.s3Secret | b64enc | quote }}
  s3-bucket: {{ .Values.api.s3Bucket | b64enc | quote }}